load("@rules_python//python:defs.bzl", "py_binary")

package(
    default_visibility = ["//visibility:public"],
)

py_binary(
    name = "project",
    srcs = ["project.py"],
    main = "project.py",
)
