exports_files([
    "diff_allowlist.sh",
    "diff_overlap.sh",
    "generated_srcs_test.sh",
    "java_runtime_jars_manifest.bzl",
    "runtime_jars_allowlist.bzl",
    "runtime_jars_overlap.bzl",
])
